name: Generate Snake

on:
  schedule:
    # Execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generates the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: imdevshiv
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Ensure the output directory exists
      - name: Create Output Directory
        run: mkdir -p dist

      # Deploy the generated files to the 'output' branch
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Show the status of the build (for debugging)
      - name: Check Git Status
        run: git status

      # Push the changes if needed
      - name: Push Changes to Master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
